apiVersion: v1
data:
  password: {{ .Values.superuser_password }}
kind: Secret
metadata:
  creationTimestamp: null
  name: kong-enterprise-superuser-password
  namespace: kong
---
apiVersion: v1
data:
  admin_gui_session_conf: {{ .Values.admin_gui_session_conf }}
  portal_session_conf: {{ .Values.portal_session_conf }}
kind: Secret
metadata:
  creationTimestamp: null
  name: kong-session-config
  namespace: kong
---
apiVersion: v1
data:
  license: {{ .Values.kong.license }}
kind: Secret
metadata:
  creationTimestamp: null
  name: kong-enterprise-license
  namespace: kong