apiVersion: v1
data:
  password: {{ .Values.superuserPassword }}
kind: Secret
metadata:
  creationTimestamp: null
  name: kong-enterprise-superuser-password
  namespace: kong
---
apiVersion: v1
data:
  admin_gui_session_conf: {{ .Values.adminGuiSessionConf }}
  portal_session_conf: {{ .Values.portalSessionConf }}
kind: Secret
metadata:
  creationTimestamp: null
  name: kong-session-config
  namespace: kong
---
apiVersion: v1
data:
  license: {{ .Values.kongEnterpriseLicense }}
kind: Secret
metadata:
  creationTimestamp: null
  name: kong-enterprise-license
  namespace: kong